// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrxzlQKpQqhWiMYCUKoB91WpenQCceRDE',
    appId: '1:795797947423:web:d80564eb33ea4d3253012a',
    messagingSenderId: '795797947423',
    projectId: 'dambe-23f3d',
    authDomain: 'dambe-23f3d.firebaseapp.com',
    storageBucket: 'dambe-23f3d.firebasestorage.app',
    measurementId: 'G-YGB5QZ2WB9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDr3L2QRds3R-h7WL5rR8AQtj_Q-igB-LM',
    appId: '1:795797947423:android:795ccd1453aa8efa53012a',
    messagingSenderId: '795797947423',
    projectId: 'dambe-23f3d',
    storageBucket: 'dambe-23f3d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1mjrdIF9BqXqhp4KziT0_sexzbo1zc-k',
    appId: '1:795797947423:ios:3f36ad9ed46e6dac53012a',
    messagingSenderId: '795797947423',
    projectId: 'dambe-23f3d',
    storageBucket: 'dambe-23f3d.firebasestorage.app',
    iosBundleId: 'com.example.dambeSugu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1mjrdIF9BqXqhp4KziT0_sexzbo1zc-k',
    appId: '1:795797947423:ios:3f36ad9ed46e6dac53012a',
    messagingSenderId: '795797947423',
    projectId: 'dambe-23f3d',
    storageBucket: 'dambe-23f3d.firebasestorage.app',
    iosBundleId: 'com.example.dambeSugu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrxzlQKpQqhWiMYCUKoB91WpenQCceRDE',
    appId: '1:795797947423:web:d6b47006a84d1c5953012a',
    messagingSenderId: '795797947423',
    projectId: 'dambe-23f3d',
    authDomain: 'dambe-23f3d.firebaseapp.com',
    storageBucket: 'dambe-23f3d.firebasestorage.app',
    measurementId: 'G-1QLZG9TDQ5',
  );
}
